services:

  #Nextjs frontend service
  nextapp:
    container_name: nextapp
    image: thomasvdz/entr-nextapp
    build:
      context: ./client/entr
      dockerfile: next.dockerfile
    ports:
      - 3000:3000
    environment:
      - TEST=http://localhost:4000
    depends_on:
      - flaskapp

  #Flask server/backend 
  flaskapp:
    container_name: flaskapp
    image: thomasvdz/entr-flaskapp
    build:
      context: ./server
      dockerfile: flask.dockerfile
    ports:
      - 4000:4000
    env_file: "./server/.env"
    depends_on:
      - db 

  #Nginx Service
  nginx:
    container_name: nginx
    image: thomasvdz/entr-nginx
    build:
      context: ./nginx
      dockerfile: nginx.dockerfile
    ports:
      - 80:80
    depends_on:
      - nextapp

  #Database Service
  db:
    container_name: db
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pgAdmin1!
      - POSTGRES_DB=entr
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}