services:

  #Nextjs frontend service
  nextapp:
    container_name: nextapp
    image: nextapp:1.0.0
    build:
      context: ./client/entr
      dockerfile: next.dockerfile
    ports:
      - 3000:3000
    environment:
      - TEST=http://localhost:4000
    depends_on:
      - flaskapp

  #Flask server/backend 
  flaskapp:
    container_name: flaskapp
    image: flaskapp:1.0.1
    build:
      context: ./server
      dockerfile: flask.dockerfile
    ports:
      - 4000:4000
    environment:

    depends_on:
      - db 


  #Database Service
  db:
    container_name: db
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: Entr
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}